function lsblka --wraps='lsblk -o NAME,MAJ:MIN,MODEL,LABEL,SIZE,FSSIZE,FSUSED,TYPE,FSTYPE,MOUNTPOINT' --description 'alias lsblka=lsblk -o NAME,MAJ:MIN,MODEL,LABEL,SIZE,FSSIZE,FSUSED,TYPE,FSTYPE,MOUNTPOINT'
  lsblk -o NAME,MAJ:MIN,MODEL,LABEL,SIZE,FSSIZE,FSUSED,TYPE,FSTYPE,MOUNTPOINT $argv; 
end
